### ISSUE TITLE
Gem cant't be install on Mac M1

### ISSUE THREAD

**Issue by jeezs** [isomorfeus/isomorfeus-project#9]
isomorfeus gem cant't be install on Mac M1, I think its because of  Nokogiri-1.10.10 dependency too old and not M1 compatible.

**Comment by janbiedermann** [comment]
Thanks, its because of isomorfeus-ferret which can't compile on M1. Unfortunately i dont have a M1 Mac available, so i currently cant fix it.

**Comment by jeezs** [comment]
in gem dependencies using nokogiri  (1.12.5 arm64-darwin) instead of nokogiri-1.10.10 might help.
I havent found where this dependency is called .

**Comment by janbiedermann** [comment]
Oh, alright, another problem, i will check, thanks, so did isomorfeus-ferret compile on your machine?

**Comment by janbiedermann** [comment]
May i ask, which version of isomorfeus did you actually install?
Cause on my side, it did pull in nokogiri 1.12.5

**Comment by jeezs** [comment]
Yes isomorfeus-ferret install correctly on the M1

**Comment by jeezs** [comment]
Don't relay know I Think it's the latest.I've install the gem using  "gem install isomorfeus"  but had the following error : `
ERROR:  Possible alternatives: isomorfeus-asset-manager, isomorfeus-ferret, isomorfeus-hamster, isomorfeus-iodine, isomorfeus-preact, isomorfeus-puppetmaster, i` so I install using "gem install isomorfeus --pre" instead

**Comment by janbiedermann** [comment]
Yes, there are no official releases, just pre-releases, so --pre is required or -v
just releases 2.0.0.rc4, you can try: `gem install isomorfeus -v 2.0.0.rc4`

**Comment by jeezs** [comment]
no luck with latest version  ` /Users/jeezs/.rvm/gems/ruby-3.0.0/extensions/arm64-darwin-20/3.0.0/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/jeezs/.rvm/gems/ruby-3.0.0/gems/nokogiri-1.10.10 for inspection.`

**Comment by janbiedermann** [comment]
`gem install isomorfeus -v 2.0.0.rc6`

found the issue, fixed in rc6

Thanks a lot !
